### PR TITLE
Fix "Culling Exclusion Zones"

### LINKED ISSUE #2158: Missing map functions after migration
### Affected versions

Development build

### Development build

_No response_

### Description

There are some functions missing after the migration. This issue is a placeholder for them. continue of #2039

- [x] Ruler
- [x] Culling can not be displayed
- [ ] The check boxes to hide and show UI stuff was not working for AAA/SAM threats

### Save game and other files

-

### PR DESCRIPTION
**Pull request by Raffson**
Partial fix #2158 

Note that `TerrainZonesLayers` comes before `CullingExclusionZones` in `LiberationMap.tsx`, though for some reason that order gets revered and I'm not sure why. It's not a critical change so I guess it'll have to do for now...

### CODE REVIEW

File: client/src/components/cullingexclusionzones/CullingExclusionZones.tsx [hunk 1]
```diff
@@ -0,0 +1,48 @@
...
+}
+
+const CullingExclusionCircles = (props: CullingExclusionCirclesProps) => {
+  return (
+    <>
+      <LayerGroup>
+        {props.zones.map((zone, idx) => {
+          return (
+            <Circle
+              key={idx}
```
Comment (DanAlbert) [inline client/src/components/cullingexclusionzones/CullingExclusionZones.tsx:17]: https://robinpokorny.medium.com/index-as-a-key-is-an-anti-pattern-e0349aece318

The index can sometimes be reliably used as a key, but I don't think this is one of those times. Nothing differentiates the first exclusion zone between two save games. If you auto load game A (open liberation where A was the most recent save), then load game B, at least the first exclusion zone probably will not be updated.

I think the only way to use indexes as keys safely is when a parent component has a unique key, which isn't the case here.

You could try doing like I did in https://github.com/dcs-liberation/dcs_liberation/commit/c5efc908dec5f854176cd4ee9dafa66323a6d777. It's a little wasteful because ephemeral entities like these will cause component redraws on every query, but there are so few of them it doesn't really matter.

Alternatively, if we add a UUID for the `Game` itself and have that be a prop of `LiberationMap`, that might be sufficient to ensure that everything on the map is redrawn when a new game loads?

**Review by DanAlbert — CHANGES_REQUESTED** [review]

File: client/src/components/cullingexclusionzones/CullingExclusionZones.tsx (hunk 1 above)
Comment (Raffson) [reply client/src/components/cullingexclusionzones/CullingExclusionZones.tsx:17]: To be honest I'm not sure, I simply based myself on `AirDefenceRangeLayer.tsx` since the principle is the same. I'll see if I can do some tests to verify that there's no unexpected behavior.

Comment (Raffson) [reply client/src/components/cullingexclusionzones/CullingExclusionZones.tsx:17]: Ok I see what you mean now, I'll give your suggestions a try and see what happens.

Comment (Raffson) [reply client/src/components/cullingexclusionzones/CullingExclusionZones.tsx:17]: I'm starting to doubt if we really need to add a UUID, cause essentially we just need to redraw culling zones whenever they change. There's multiple ways for this to happen and each of them ought to trigger a redraw on the map. Because of this I believe your second suggestion will only solve part of the problem, i.e. only when a (new) game is loaded. However if you go into your settings and change the culling distance, it ought to redraw the zones too, or at least that's what happens on v5.2 which I assume is correct behavior.

I believe the following situations ought to trigger a redraw:
 
- Changes to the culling distance setting
- Loading a (new) game
- Changes to the battlefield??? like base capture?

Any other suggestions?

Comment (DanAlbert) [reply client/src/components/cullingexclusionzones/CullingExclusionZones.tsx:17]: The UUID done the way I pointed to (that is, badly, by generating an ephemeral UUID every time the zones are queried) would be enough to ensure that an old zone is not redrawn. The part we're missing is handling of the `unculled_zones_updated` field in the event stream. That'll be true whenever the zones should be requeried. Forgot that we weren't already handling that. I think if you add the UUID to use as a key and also handle that field, that'll work.

If you want to avoid the UUID, you could instead create the key based on the position and the radius (just concatenating them would be enough). Either way, you do need to listen for the push events.

Feel free to update the event stream model if the boolean isn't the way you want to go about this. You could replace that with something like:

```json
"unculled_zones": {
  "updated": true,
  "radius": 10,
  "points": [
    {"lat": 20, "lng": 30}
  ]
}
```

And fully replace the existing zones whenever that `updated` field is true (and ignore it otherwise).

I don't know if that's better or worse than the current field. My point is that it's not set in stone, so whatever API makes the server/UI code cleanest is fine with me.

Comment (Raffson) [reply client/src/components/cullingexclusionzones/CullingExclusionZones.tsx:17]: I've been at it for several hours now and I'm getting closer, though I noticed unculled zones aren't the only ones that are being difficult. There are ways to mess up the threat zones as well.
EDIT: is that what's meant with the last point of the referenced issue?

I'm slowly making progress but it's due to the fact that a lot of things have been missed. Currently I got changes in 11 files and it's not over yet, though once I get it working I'll make sure to review it all.

Also, in `settings.py` I found the following code:

````
perf_culling_distance: int = bounded_int_option(
    "Culling distance (km)",
    page=MISSION_GENERATOR_PAGE,
    section=PERFORMANCE_SECTION,
    default=100,
    min=10,
    max=10000,
    causes_expensive_game_update=True,
)
perf_do_not_cull_threatening_iads: bool = boolean_option(
    "Do not cull threatening IADS",
    page=MISSION_GENERATOR_PAGE,
    section=PERFORMANCE_SECTION,
    default=True,
)
perf_do_not_cull_carrier: bool = boolean_option(
    "Do not cull carrier's surroundings",
    page=MISSION_GENERATOR_PAGE,
    section=PERFORMANCE_SECTION,
    default=True,
    causes_expensive_game_update=True,
)
````

Why does the carrier's culling option trigger an update and while the threatening iads option doesn't? Is this a mistake? Should it be both? Or none?

Comment (DanAlbert) [reply client/src/components/cullingexclusionzones/CullingExclusionZones.tsx:17]: It's possible. I'm not very familiar with how culling works because I don't use it.

Comment (Raffson) [reply client/src/components/cullingexclusionzones/CullingExclusionZones.tsx:17]: Ok I think I understand why. When looking at `game.py` in `compute_unculled_zones` I can't find anything referencing the iads option. My guess it the option doesn't work at this time, therefore no need to send updates...

Comment (Raffson) [reply client/src/components/cullingexclusionzones/CullingExclusionZones.tsx:17]: More progress, I have something that works more or less, a UUID is really not needed as far as I understand, the index will do. I notice a lot of the components are just not linked correctly to their slices. It's probably one of the problems left in my solution since I can change saves and display the correct culling zones, but it's not staying on the map, i.e. the culling option disables automatically. The same happens when changing the culling distance option, which is unacceptable because you want to see how the zones change while changing the value.

Either way, I believe I'm close now...

Comment (Raffson) [reply client/src/components/cullingexclusionzones/CullingExclusionZones.tsx:17]: Turns out I still had a stupid bug left, so I got it working. Now it's just a matter of filtering out the stuff that's irrelevant...

Comment (Raffson) [reply client/src/components/cullingexclusionzones/CullingExclusionZones.tsx:17]: Solution pushed! It a big one though, I can comment like I did for end-game mechanics if that makes it easier for you.

As I mentioned earlier, the threat zones are still a problem, you can show the "full" overlay, cheat-capture a point and it will only update the first time, subsequent captures don't adjust the overlay. It's probably the next thing I'll tackle...

**Comment by Raffson** [comment]
Let me fix the merge-conflict real quick....

File: client/src/api/_liberationApi.ts [hunk 2]
```diff
@@ -479,6 +479,7 @@ export type Game = {
   threat_zones: ThreatZoneContainer;
   navmeshes: NavMeshes;
   map_center?: LatLng;
+  unculled_zones: UnculledZone[];
```
Comment (Raffson) [inline client/src/api/_liberationApi.ts:482]: Required for gameLoaded in `unculledZonesSlice`

File: client/src/api/eventstream.tsx [hunk 3]
```diff
@@ -87,6 +88,16 @@ export const handleStreamedEvents = (
...
+  if (events.unculled_zones_updated) {
+    backend.get(`/map-zones/unculled`).then(
+      (result) => {
+        if (result.data) {
+          dispatch(unculledZonesUpdated(result.data));
+        }
+      }
+    );
+  }
+
```
Comment (Raffson) [inline client/src/api/eventstream.tsx:100]: Check for `unculled_zones_updated` event, using `backend.get` to retrieve a list of `UnculledZoneJs` objects. Pass the data to `unculledZonesUpdated`, i.e. line 18 in `unculledZonesSlice.ts`.

File: client/src/api/unculledZonesSlice.ts [hunk 4]
```diff
@@ -0,0 +1,36 @@
...
+  zones: [],
+};
+
+export const unculledZonesSlice = createSlice({
+  name: "unculledZonesState",
+  initialState,
+  reducers: {
+    updated: (state, action: PayloadAction<UnculledZone[]>) => {
+      state.zones = action.payload;
+    },
```
Comment (Raffson) [inline client/src/api/unculledZonesSlice.ts:20]: This should trigger the front-end to redraw, however in order for this to work you must reference it using `selectUnculledZones` using the "AppSelector" as is done on line 32 of `CullingExclusionZones.tsx`

File: client/src/api/unculledZonesSlice.ts [hunk 5]
```diff
@@ -0,0 +1,36 @@
...
+  },
+  extraReducers: (builder) => {
+    builder.addCase(gameLoaded, (state, action) => {
+      state.zones = action.payload.unculled_zones;
+    });
+    builder.addCase(gameUnloaded, (state) => {
+      state.zones = initialState.zones;
+    });
```
Comment (Raffson) [inline client/src/api/unculledZonesSlice.ts:28]: Updates for when the game is loaded/unloaded, this is why the API of Game had to include the `unculled_zones`

File: client/src/components/cullingexclusionzones/CullingExclusionZones.tsx [hunk 6]
```diff
@@ -0,0 +1,47 @@
...
+            />
+          );
+        })}
+      </LayerGroup>
+    </>
+  );
+};
+
+export default function CullingExclusionZones() {
+  const data = useAppSelector(selectUnculledZones).zones;
```
Comment (Raffson) [inline client/src/components/cullingexclusionzones/CullingExclusionZones.tsx:32]: This assures that updates that arrive in the slice, get pushed through, using `useListUnculledZonesQuery` like before doesn't do what I expected. If I had to guess, it queries the zones from the front-end instead of the back-end.

File: client/src/components/cullingexclusionzones/CullingExclusionZones.tsx [hunk 7]
```diff
@@ -0,0 +1,47 @@
...
+  var cez = <></>;
+
+  if (!data) {
+    console.log("Empty response when loading culling exclusion zones");
+  } else {
+    cez = (
+      <CullingExclusionCircles zones={data}></CullingExclusionCircles>
```
Comment (Raffson) [inline client/src/components/cullingexclusionzones/CullingExclusionZones.tsx:39]: I noticed that adding a key here can bring the culling option back to the bottom of the list like it used to be, but <ins>it can't be variable</ins>! When it's variable, unculled zones can simply disappear from the map upon receiving updates, forcing you to turn the option back on. It's like turning the culling option off...

File: game/game.py [hunk 8]
```diff
@@ -514,6 +514,7 @@ def compute_unculled_zones(self) -> None:
             zones.append(package.target.position)
 
         self.__culling_zones = zones
+        events.update_unculled_zones()
```
Comment (Raffson) [inline game/game.py:517]: Add missing event-logic to `compute_unculled_zones`, justifies the other changes in the file...

File: game/server/game/models.py [hunk 9]
```diff
@@ -28,6 +28,7 @@ class GameJs(BaseModel):
     threat_zones: ThreatZoneContainerJs
     navmeshes: NavMeshesJs
     map_center: LeafletPoint | None
+    unculled_zones: list[UnculledZoneJs]
```
Comment (Raffson) [inline game/server/game/models.py:31]: Back-end changes for changing the API, required for `gameLoaded` in `unculledZonesSlice`

File: game/server/mapzones/models.py [hunk 10]
```diff
@@ -28,6 +28,16 @@ class UnculledZoneJs(BaseModel):
...
+    @staticmethod
+    def from_game(game: Game) -> list[UnculledZoneJs]:
+        return [
+            UnculledZoneJs(
+                position=zone.latlng(),
+                radius=game.settings.perf_culling_distance * 1000,
+            )
+            for zone in game.get_culling_zones()
+        ]
+
```
Comment (Raffson) [inline game/server/mapzones/models.py:40]: Refactored this from `game/server/mapzones/routes.py` since we need this in on line 48 `game/server/game/models.py`

File: qt_ui/windows/settings/QSettingsWindow.py [hunk 11]
```diff
@@ -356,8 +358,9 @@ def applySettings(self):
             self.cheat_options.show_base_capture_cheat
         )
 
-        self.game.compute_unculled_zones()
+        self.game.compute_unculled_zones(GameUpdateEvents())
         GameUpdateSignal.get_instance().updateGame(self.game)
+        EventStream.put_nowait(GameUpdateEvents().update_unculled_zones())
```
Comment (Raffson) [inline qt_ui/windows/settings/QSettingsWindow.py]: When changing culling options, these don't seem to get pushed unless we do it here. I would expect the `GameUpdateSignal` to take care of that, but that doesn't seem to be the case. I assume it's because `GameUpdateEvents` isn't static due to the dataclass decorator, which is probably why events seem to disappear. Therefore it could be interesting to drop the dataclass decorator so that it mimics a static class, though that could have unintended consequences I am not aware of yet.

File: client/src/api/eventstream.tsx (hunk 3 above)
Comment (Raffson) [reply client/src/api/eventstream.tsx:100]: I tried using `backend.get` for the threat zones and that seems to fix the problem I described earlier, being that the threat zones don't update after a first cheat-capture. I'll probably start on a new PR for that soon, and along the way iron out similar issues with the map components.

File: client/src/components/cullingexclusionzones/CullingExclusionZones.tsx (hunk 6 above)
Comment (DanAlbert) [reply client/src/components/cullingexclusionzones/CullingExclusionZones.tsx:32]: `useListUnculledZonesQuery` does query the backend, but there's automatic caching to reduce unnecessary calls. The auto-generator needs to be told how to invalidate the cache though, and that probably wasn't set up for this query yet.

Ditching it and pushing the data into redux is totally fine with me though. It's often the easier approach IME.

File: qt_ui/windows/settings/QSettingsWindow.py (hunk 11 above)
Comment (DanAlbert) [reply qt_ui/windows/settings/QSettingsWindow.py]: `GameUpdateSignal`'s existence is a bug, essentially. It's the source of a lot of bad UI performance because it's far too broad a signal. We don't want to increase reliance on it because we're actively trying to remove it (and the rest of Qt).

Comment (DanAlbert) [inline qt_ui/windows/settings/QSettingsWindow.py]:
```suggestion
        events = GameUpdateEvents()
        self.game.compute_unculled_zones(events)
        EventStream.put_nowait(events)
        GameUpdateSignal.get_instance().updateGame(self.game)
```

**Review by DanAlbert — CHANGES_REQUESTED** [review]

**Review by DanAlbert — APPROVED** [review]
