### PR TITLE
Fix for NavMeshes & ThreatZones

### LINKED ISSUE #2253: Not all map features updating properly
### Affected versions

Development build

### Development build

_No response_

### Description

I found that many functions on the map are not updating properly. Things like the `ThreatZones` and `NavMeshes` in the left menu only update once, after that it seems to be getting the same data over and over again. Options on right side like "Ships", "Factories", "Air defences", etc. seem to be FUBAR as well. Also supply routes were not being drawn in the correct color after a capture event. So yeah, I think I found a new issues to solve 🤣 

An overview:

- [x] ThreatZones not updating after first update
- [x] Navmeshes not updating after first update
- [x] SupplyRoutes not updating at all
- [x] Air defences: FUBAR
- [x] Factories: FUBAR
- [x] Ships : FUBAR
- [x] Other ground objects: FUBAR
- [x] Active combat: doesn't remove lines when combat ends (dead units should be erased after some period?)
- [x] Allied/Enemy IADS network: doesn't seem to do anything, using some debug messages I can see connections that are linked with themselves

### Save game and other files

Any campaign should do since it's mostly front-end stuff...

### LINKED ISSUE #2263: Push-based events overhaul
### Affected versions

Development build

### Development build

_No response_

### Description

Opening this issue to keep better track of the overhaul, labeling it (performance) bug/UX because fixing this will improve the UX since the map will update faster, more towards what we're used to from v5.2. Consider this as the first phase, effectively being a clean-up of `eventstream.tsx` to eliminate get-requests that are sent from the front-end as much as possible:

- [x] Navmesh updates (#2254)
- [x] Unculled zones (#2264)
- [x] Threat zones (#2254)
- [x] Updated flights (#2265)
- [x] Updated front lines (#2266)
- [x] Updated Tgos (#2269)
- [x] Updated IADS (#2262)
- [x] Updated control points (#2267)
- [x] Updated supply routes (#2255)
- [x] Combat updates: redundancies present (#2268)

Did I miss anything?

### Save game and other files

N/A

### PR DESCRIPTION
**Pull request by Raffson**
Partial fix #2253 
Partial fix #2263 

Should temporarily fix the first two issues until we find a better solution...

### CODE REVIEW

**Comment by DanAlbert** [comment]
This is "fixing" the caching problem by just undoing the caching. I don't know how I feel about this. We may not rely much on caching for performance today (the amount of data that will have a cache hit is pretty low, and it's all happening on localhost), but I worry that it'll be harder to go through and migrate to rtk query later if we avoid it in the beginning.

https://github.com/dcs-liberation/dcs_liberation/blob/develop/client/src/api/liberationApi.ts is where the cache invalidation rules are set up, but those don't actually interop with streamed updates. I think to allow streamed updates to invalidate the cache, we need to do https://redux-toolkit.js.org/rtk-query/usage/streaming-updates?

I'm curious to hear what others think. RTK Query does some powerful things, but I've found it quite difficult to use, so maybe we should just abandon it. If that's the case, we should also investigate an alternative ASAP, because we still want auto-generated APIs, and will probably need to rework a lot of callsites to switch to a new generator.

**Comment by Raffson** [comment]
Converting back to draft since I'm planning to improve the communication between front- & back-end

**Comment by Raffson** [comment]
Push-based update logic is in place, currently updates are done for the entire navmesh for each coalition separately, the same goes for the threat zones. Since navmeshes get recomputed every once in a while, I don't see a way around pushing the entire thing. For threat zones however this could change if the re-computation of threat zones would keep track of which specific threat zones changed, but that's an issue on its own...

File: client/src/api/navMeshSlice.ts [hunk 1]
```diff
@@ -22,12 +22,15 @@ const navMeshSlice = createSlice({
...
   reducers: {
-    updated: (state, action: PayloadAction<INavMeshUpdate>) => {
-      const polys = action.payload.mesh.polys;
-      if (action.payload.blue) {
-        state.blue = polys;
-      } else {
-        state.red = polys;
+    updated: (state, action: PayloadAction<INavMeshUpdate[]>) => {
+      for (const [blue, navmesh] of Object.entries(action.payload)) {
+        const data = {blue: (blue === "true"), mesh: navmesh} as unknown as INavMeshUpdate
```
Comment (DanAlbert) [inline client/src/api/navMeshSlice.ts:27]: What's going on here?

File: client/src/api/threatZonesSlice.ts [hunk 2]
```diff
@@ -24,12 +24,24 @@ const initialState: ThreatZonesState = {
...
+
 export const threatZonesSlice = createSlice({
   name: "threatZonesState",
   initialState,
   reducers: {
-    updated: (state, action: PayloadAction<ThreatZoneContainer>) => {
-      state.zones = action.payload;
+    updated: (state, action: PayloadAction<IThreatZoneUpdate[]>) => {
+      for (const [blue, zones] of Object.entries(action.payload)) {
+        const data = {blue: (blue === "true"), zones: zones} as unknown as IThreatZoneUpdate
```
Comment (DanAlbert) [inline client/src/api/threatZonesSlice.ts:38]: Ditto

File: client/src/api/navMeshSlice.ts (hunk 1 above)
Comment (Raffson) [reply client/src/api/navMeshSlice.ts:27]: TSC being very annoying...

Python has no problems making a dictionary that maps a boolean to some object, but typescript doesn't want to play ball. It replaces it by taking the boolean value and transforming it to a string that maps to the navmesh. When I try recasting without the "as unknown" part, TSC complains that navmesh has no property "polys", though I know for a fact it does. It's part of the ugliness I described on discord...

File: client/src/api/threatZonesSlice.ts (hunk 2 above)
Comment (Raffson) [reply client/src/api/threatZonesSlice.ts:38]: Same answer...

File: client/src/api/navMeshSlice.ts (hunk 1 above)
Comment (DanAlbert) [reply client/src/api/navMeshSlice.ts:27]: Can you use a record instead? Object keys must be numbers or strings, but the `Record` type is a true key/value pair.

Comment (Raffson) [reply client/src/api/navMeshSlice.ts:27]: I'll give that a try today 👍

Comment (Raffson) [reply client/src/api/navMeshSlice.ts:27]: > Can you use a record instead? Object keys must be numbers or strings, but the `Record` type is a true key/value pair.

It seems like that doesn't change much, TSC is still asking for a number, string or symbol for the keys. Suppose I leave the "as unknown" in the NavMeshes part then I get the following error:

> TS2352: Conversion of type '{ blue: boolean; mesh: INavMeshUpdate; }' to type 'INavMeshUpdate' may be a mistake because neither type sufficiently overlaps with the other. <ins>If this was intentional, convert the expression to 'unknown' first.</ins>
Types of property 'mesh' are incompatible.
Property 'polys' is missing in type 'INavMeshUpdate' but required in type 'NavMesh'.

So TSC is literally suggesting the cast-to-unknown solution, though I'm definitely not a fan of this either...

Comment (DanAlbert) [reply client/src/api/navMeshSlice.ts:27]: Okay. Yuck. I hate it but you're right that there doesn't appear to be another option. Thanks for trying though.

**Review by DanAlbert — APPROVED** [review]
Ready to merge, but conflicts need to be resolved.
